proyecto/config/urls.py
from django.contrib import admin
from django.urls import path, include 
#from config import views

urlpatterns = [
    path('',include("core.urls")),
    path('admin/', admin.site.urls),
    path('libros/',include("libros.urls")),
    path('ventas/',include("ventas.urls")),
    #path('saludo/', views.saludo),
    #path('nombre/<nombre>/<apellido>', views.nombre),
    #path('mi_html/', views.probando),
    #path('tupla/',views.tupla),
    #path('lista/',views.lista)
]

proyecto/core/urls.py
from django.urls import path
from core.views import index, CustomLoginViews, register
from django.contrib.auth.views import LogoutView

app_name = "core"

urlpatterns = [
    path("", index, name="index"),
    path("login/", CustomLoginViews.as_view(), name="login"),
    path("logout/",LogoutView.as_view(template_name = "core/logout.html"), name="logout"),
    path("register/",register,name="register")
]

proyecto/libros/urls.py
from django.urls import path
from libros.views import lista_libros, libros_create, lista_autores, LibroDetail, LibroUpdate, LibroDelete, Nosotros
#from config import views

app_name = "libros"
urlpatterns = [
    path("", Nosotros, name="nosotros"),
    path("libros/lista",lista_libros, name="lista_libros"),
    path("libros/create",libros_create,name="libros_create"),
    path("libros/autores",lista_autores,name="lista_autores"),
    path("libros/detail/<int:pk>",LibroDetail.as_view(),name="libro_detail") ,
    path("libros/update/<int:pk>",LibroUpdate.as_view(),name="libro_update"),
    path("libros/delete/<int:pk>",LibroDelete.as_view(),name="libro_delete")
]

proyecto/ventas/urls.py
from django.urls import path
from ventas.views import VentasList, VentasCreate, VentasDetail, VentasUpdate, VentasDelete
#from config import views

app_name = "ventas"
urlpatterns = [
    path("ventas/lista",VentasList.as_view(),name="ventas_lista"),
    path("ventas/create", VentasCreate.as_view(), name="ventas_create"),
    path("ventas/detail/<int:pk>",VentasDetail.as_view(),name="ventas_detail"),
    path("ventas/update/<int:pk>",VentasUpdate.as_view(),name="ventas_update"),
    path("ventas/delete/<int:pk>",VentasDelete.as_view(),name="ventas_delete")
]

proyecto/core/models.py
from django.db import models

# Create your models here.

proyecto/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

class CustomAuthenticationForm(AuthenticationForm):
    class Mete:
        model = User
        fields = ["username", "password"]

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username","password1","password2"]

proyecto/core/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from .forms import CustomAuthenticationForm, CustomUserCreationForm
from django.http import HttpResponse, HttpRequest

def index(request):
    return render(request,"core/index.html")

class CustomLoginViews(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "core/login.html"

def register(request: HttpRequest):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            form.save()
            return render(request, "core/index.html", {"mensaje": f"Usuario '{username}' creado correctamente"})
    else:
        form = CustomUserCreationForm
    return render(request, "core/register.html",{"form": form})

proyecto/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>
        
        {% block titulo %}
        {% endblock titulo %}   
     
    </title>
    <!-- Favicon-->
    
    <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" />
    <!-- Core theme CSS (includes Bootstrap)-->

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container px-5">
            <a class="navbar-brand" href="#!">Libreria</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Inicio</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'libros:lista_libros' %}">Libros</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'libros:lista_autores' %}">Autores</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'libros:nosotros' %}">Nosotros</a></li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <form action="{% url 'core:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-dark ">Logout</button>
                        </form>
                    <li class="nav-item bg-secondary"><a class="nav-link" href="#">{{ user.username }}</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'ventas:ventas_lista' %}">Ventas</a></li>
                        
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'core:login' %}">Login</a></li>
                    {% endif %}   
                </ul>
            </div>
        </div>
    </nav>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <div class="container px-4 py-lg-4">
        <div class="row align-items-center my-1">
            <h1 class="display-4 text-center mb-4 bg-dark text-white ">
                {% block body_title %}
                {% endblock body_title %}
            </h1>
        </div>
        {% block content %}
        {% endblock content %}
    </div>
    

    {% block contenido %}
    {% endblock contenido %}

    <footer class="py-3 bg-dark fixed-bottom" style="bottom: 0; width: 100%;">
        <div class="container px-4 px-lg-5">
            <p class="m-0 text-center text-white small">Copyright &copy; Libreria sitio web</p>
        </div>
    </footer>
     <!-- Bootstrap core JS-->
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
     <!-- Core theme JS-->
     <script src="{% static 'core/js/scripts.js' %}"></script>
</body>
</html>

proyecto/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block titulo %}
    PROYECTO
 {% endblock titulo %}
 
 {% block body_title %}
        Libreria Leone
 {% endblock body_title %}

 {% block contenido %}
    <!-- Page Content-->
    <div class="container px-4 px-lg-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="text-center">
        {% if user.is_authenticated %}
            <p class = "font-weight-bold"> ¡Bienvenido! {{user.username}}</p>
        {% endif %}

        {% if mensaje %}
        <p class="font-weight-bold"> {{mensaje}} ¡Bienvenido!</p>
        {% endif %}
                </div>
             </div>
           </div>
        </div>
        <!-- Heading Row-->
        <div class="row gx-4 gx-lg-5 my-5">
            <div class="col-lg-7 mb-4 mb-lg-0">
                <img class="img-fluid rounded" src="{% static 'core/img/82162.webp' %}" alt="..." />
            </div>
            <div class="col-lg-5 text-center mt-lg-0 mt-4">
                <h2 class="font-weight-light mt-0">Catálogo</h2>
                <p class="mb-4">Nuestra librería dispone de un amplio catálogo de libros, de toda variedad de géneros, editoriales y autores. En nuestro catálogo podras realizar búsquedas tanto por nombre del libro como por el autor. Podras realizar compras de forma online o presencial.</p>
                <a class="btn btn-dark" href="{% url 'libros:lista_libros' %}">Ir Al Catálogo</a>
                <br>
                <br>
                <br>
                <br>
                <br>
                <h2 class="font-weight-light mt-0">Autores</h2>
                <p class="mb-4">Aqui podras ver la amplia lista de autores y los libros que disponemos de cada uno de ellos. Disponemos de toda variedad de autores clasicos, asi como los mejores escritores contemporaneos.</p>
                <a class="btn btn-dark" href="{% url 'libros:lista_autores' %}">Ir A Autores</a>
            </div>
        </div>

        <!-- Content Row-->
        <div class="row gx-4 gx-lg-5">
            <div class="col-md-4 mb-5">
                <div class="card h-100">
                    <div class="card-body">
                        <h2 class="card-title text-center">Redes Sociales</h2>
                        <br>
                        <br>
                        <div class="container">
                            <div class="row">
                                <div class="col-4 text-center">
                                    <a href="#" class="fa fa-facebook fa-lg text-dark"></a>
                                </div>
                                <div class="col-4 text-center">
                                    <a href="#" class="fa fa-twitter fa-lg text-dark"></a>
                                </div>
                                <div class="col-4 text-center">
                                    <a href="#" class="fa fa-google-plus fa-lg text-dark"></a>
                                </div>
                            </div>
                            <br>
                            <br>
                            <div class="row">
                                <div class="col-4 text-center">
                                    <a href="#" class="fa fa-youtube fa-lg text-dark"></a>
                                </div>
                                <div class="col-4 text-center">
                                    <a href="#" class="fa fa-linkedin fa-lg text-dark"></a>
                                </div>
                                <div class="col-4 text-center">
                                    <a href="#" class="fa fa-instagram fa-lg text-dark"></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-5">
                <div class="card h-100">
                    <div class="card-body">
                        <h2 class="card-title text-center">Sucursales</h2>
                        <br>
                        <ul>
                            <li> 📍 Cordoba 1234. Rosario, Santa Fe, Argentina</li>
                            <br>
                            <li> 📍 San Lorenzo 3836. Rosario, Santa Fe, Argentina</li>
                            <br>
                            <li> 📍 Mitre 365. Rosario, Santa Fe, Argentina</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-5">
                <div class="card h-100">
                    <div class="card-body">
                        <h2 class="card-title">Contacto</h2>
                        <br>
                        <br>
                        <ul>
                            <li> ☎️ 3416893209</li>
                            <br>
                            <li> 📧 librerialeone@gmail.com</li>
                            <br>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
 {% endblock contenido %}

proyecto/core/templates/core/login.html
{% extends 'core/base.html' %}
  
{% block titulo %}
       Login
 {% endblock titulo %}

 {% block body_title %}
        Login
 {% endblock body_title %}

{% block contenido %}
 <form method="post">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="hidden" name="next" value="{% url 'core:index' %}">
    <button type="submit" class="btn btn-primary ">Iniciar Sesion</button>
    <a href="{% url 'core:index' %}" class="btn btn-secondary ">Cancelar</a>
 </form>
 {% endblock contenido %}

proyecto/core/templates/core/logout.html
{% extends 'core/base.html' %}
  
{% block titulo %}
       Login
 {% endblock titulo %}

 {% block body_title %}
        Logout
 {% endblock body_title %}

{% block contenido %}
<div class="container">
       <div class="row justify-content-center">
           <div class="col-lg-8">
               <div class="text-center">
                     <br>
                     <br>         
                     <p class="font-weight-bold">Has cerrado sesion. ¡Hasta Luego!</p>
               </div>
           </div>
       </div>
   </div>
 {% endblock contenido %}

proyecto/core/templates/core/register.html
{% extends 'core/base.html' %}
  
{% block titulo %}
       Login
 {% endblock titulo %}

 {% block body_title %}
        Login
 {% endblock body_title %}

{% block contenido %}
 <form method="post">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="hidden" name="next" value="{% url 'core:index' %}">
    <button type="submit" class="btn btn-primary ">Iniciar Sesion</button>
    <a href="{% url 'core:index' %}" class="btn btn-secondary ">Cancelar</a>
 </form>
 {% endblock contenido %}