proyecto/config/urls.py
from django.contrib import admin
from django.urls import path, include 
#from config import views

urlpatterns = [
    path('',include("core.urls")),
    path('admin/', admin.site.urls),
    path('libros/',include("libros.urls")),
    path('ventas/',include("ventas.urls")),
    #path('saludo/', views.saludo),
    #path('nombre/<nombre>/<apellido>', views.nombre),
    #path('mi_html/', views.probando),
    #path('tupla/',views.tupla),
    #path('lista/',views.lista)
]

proyecto/core/urls.py
from django.urls import path
from core.views import index, CustomLoginViews, register
from django.contrib.auth.views import LogoutView

app_name = "core"

urlpatterns = [
    path("", index, name="index"),
    path("login/", CustomLoginViews.as_view(), name="login"),
    path("logout/",LogoutView.as_view(template_name = "core/logout.html"), name="logout"),
    path("register/",register,name="register")
]

proyecto/ventas/urls.py
from django.urls import path
from ventas.views import VentasList, VentasCreate, VentasDetail, VentasUpdate, VentasDelete
#from config import views

app_name = "ventas"
urlpatterns = [
    path("ventas/lista",VentasList.as_view(),name="ventas_lista"),
    path("ventas/create", VentasCreate.as_view(), name="ventas_create"),
    path("ventas/detail/<int:pk>",VentasDetail.as_view(),name="ventas_detail"),
    path("ventas/update/<int:pk>",VentasUpdate.as_view(),name="ventas_update"),
    path("ventas/delete/<int:pk>",VentasDelete.as_view(),name="ventas_delete")
]

proyecto/ventas/models.py
from django.contrib.auth.models import User
from django.db import models
from django.forms import ValidationError
from django.utils import timezone


# Create your models here.
class Vendedor(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    celular = models.CharField(max_length=100)
    avatar = models.ImageField(upload_to="avatares", null=True, blank=True)
  
    def __str__(self) -> str:
        return self.usuario.username


class Venta(models.Model):
    vendedor = models.ForeignKey(Vendedor, on_delete=models.SET_NULL, null=True, blank=True)
    libro = models.ForeignKey("libros.Libro", on_delete=models.DO_NOTHING)
    cantidad = models.PositiveIntegerField()
    precio_total = models.DecimalField(max_digits=10, decimal_places=2, editable=False)
    fecha_venta = models.DateTimeField(editable=False, default=timezone.now)

    class Meta:
        ordering = ("-fecha_venta",)

    def clean(self):
        if self.cantidad > self.libro.unidades:
            raise ValidationError("La cantidad vendida no puede ser mayor a la cantidad disponible")

    def save(self, *args, **kwargs):
        self.precio_total = self.libro.precio * self.cantidad
        super().save(*args, **kwargs)


    def resta(self, *args, **kwargs):
        self.libro.unidades -= self.cantidad
        self.libro.unidades.save()
        super().save(*args, **kwargs)

proyecto/ventas/forms.py
from django import forms
from . import models

class VentasForms(forms.ModelForm):
    class Meta:
        model = models.Venta
        fields = "__all__"

proyecto/ventas/views.py
from django.shortcuts import render, redirect
from ventas.models import Vendedor, Venta
from django.views.generic import DetailView, UpdateView, DeleteView, ListView, CreateView
from django.urls import reverse_lazy
from django.db.models import Q
from django.db.models.query import QuerySet
from ventas.forms import VentasForms


class VentasList(ListView):
    model = Venta
    context_object_name = "vendedores"
    template_name = "venta_list.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        busqueda = self.request.GET.get("busqueda")
        if busqueda:
            queryset = Venta.objects.filter(vendedor__icontains = busqueda)
        return queryset
      

class VentasCreate(CreateView):
    model = Venta
    form_class = VentasForms
    success_url = reverse_lazy("ventas:ventas_lista")


class VentasDetail(DetailView):
    model = Venta


class VentasUpdate(UpdateView):
    model = Venta
    form_class = VentasForms
    success_url = reverse_lazy("ventas:ventas_lista")


class VentasDelete(DeleteView):
    model = Venta
    success_url = reverse_lazy("ventas:ventas_lista")

proyecto/ventas/templates/ventas/venta_confirm_delete.html
{% extends 'core/base.html' %}
   
{% block titulo %}
       Eliminar Venta
 {% endblock titulo %}

 {% block body_title %}
      Eliminar Venta
 {% endblock body_title %}

{% block contenido %}
   <p class="fs-5"><span style="font-family: 'Georgia', serif;">¿Seguro que desea eliminar esta venta?</span></p>
   <form action="" method="post">
    {% csrf_token %}
    <button type="submit">Eliminar</button>
   </form>
   <a href="{% url 'ventas:ventas_lista' %}" class="btn btn-secondary btn-sm">Volver</a>
 {% endblock contenido %}

proyecto/ventas/templates/ventas/venta_detail.html
{% extends 'core/base.html' %}
  
{% block titulo %}
    Lista de Libros
{% endblock titulo %}

{% block body_title %}
    Detalle De La Venta
{% endblock body_title %}

{% block contenido %}
    <div class="container">
        <ul class="list-group">
            <li class="list-group-item">
                <p class="fs-4 mb-0 font-weight-bold"> Vendodor: {{venta.vendedor.usuario.username}}</p>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item fs-6"><span class="font-weight-bold">Libro:</span> {{venta.libro.nombre_libro}}</li>
                    <li class="list-group-item fs-6"><span class="font-weight-bold">Cantidad:</span> {{venta.cantidad}}</li>
                    <li class="list-group-item fs-6"><span class="font-weight-bold">Precio total:</span> {{venta.precio_total}}</li>
                    <li class="list-group-item fs-6"><span class="font-weight-bold">Fecha:</span> {{venta.fecha_venta}}</li>
                </ul>
            </li>
        </ul>
        <a href="{% url 'ventas:ventas_lista' %}" class="btn btn-dark mt-3">Volver</a>
    </div>
{% endblock contenido %}

proyecto/ventas/templates/ventas/venta_form.html
{% extends 'core/base.html' %}
   
{% block titulo %}
    Agregar libro
 {% endblock titulo %}

 {% block body_title %}
      {% if form.instance.pk %}
       Editar Venta
      {% else %}
      Agregar Nueva Venta
      {% endif %}
 {% endblock body_title %}

 {% block contenido %}
 <form action="" method="post">
  {% csrf_token %}
  {{ form }}
 <div style="margin-top: 10px;">
     <a href="{% url 'ventas:ventas_lista' %}" class="btn btn-secondary btn-sm">Volver</a>
     <button type="submit" class="btn btn-info btn-sm me-2">Guardar</button> 
 </div>
</form>
{% endblock contenido %}

proyecto/ventas/templates/ventas/venta_list.html
{% extends 'core/base.html' %}
  
{% block titulo %}
    Libros
{% endblock titulo %}

{% block body_title %}
    Ventas
{% endblock body_title %}

{% block contenido %}
<form class="mb-3 row" action="{% url 'ventas:ventas_lista' %}" method="get">
    <div class="col-auto">
        <input type="text" class="form-control" name="busqueda" placeholder="Buscar libro...">
    </div>
    <div class="col-auto">
        <button type="submit" class="btn btn-dark ">Buscar</button>
    </div>
</form>
<div class="d-flex justify-content-between align-items-center mb-3">
    <h2>Ventas</h2>
    {% if user.is_authenticated %}
    <a href="{% url 'ventas:ventas_create' %}" class="btn btn-dark btn-lg me-2 my-button">Agregar Venta</a>
    {% endif %}
</div>
<ul class="list-group">
    {% for venta in vendedores %}
    <li class="list-group-item">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <span style="font-family: 'Georgia', serif; font-size: 1.1em;">{{venta.vendedor.usuario.username}}</span>
            </div>
            <div class="d-flex align-items-center">
                <span class="me-3" style="font-family: 'Montserrat', sans-serif; font-size: 0.9em;"><strong>$</strong>{{venta.precio_total}}</span>
                <div>
                    {% if user.is_authenticated %}
                    <a href="{% url 'ventas:ventas_detail' venta.id %}" class="btn btn-dark btn-sm me-2">Ver Detalle</a>
                    <a href="{% url 'ventas:ventas_update' venta.id %}" class="btn btn-secondary btn-sm me-2">Cambiar</a>
                    <a href="{% url 'ventas:ventas_delete' venta.id %}" class="btn btn-secondary btn-sm">Borrar Venta</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </li>
{% endfor %}
</ul>
{% endblock contenido %}