proyecto/config/urls.py
from django.contrib import admin
from django.urls import path, include 
#from config import views

urlpatterns = [
    path('',include("core.urls")),
    path('admin/', admin.site.urls),
    path('libros/',include("libros.urls")),
    path('ventas/',include("ventas.urls")),
    #path('saludo/', views.saludo),
    #path('nombre/<nombre>/<apellido>', views.nombre),
    #path('mi_html/', views.probando),
    #path('tupla/',views.tupla),
    #path('lista/',views.lista)
]

proyecto/core/urls.py
from django.urls import path
from core.views import index, CustomLoginViews, register
from django.contrib.auth.views import LogoutView

app_name = "core"

urlpatterns = [
    path("", index, name="index"),
    path("login/", CustomLoginViews.as_view(), name="login"),
    path("logout/",LogoutView.as_view(template_name = "core/logout.html"), name="logout"),
    path("register/",register,name="register")
]

proyecto/libros/urls.py
from django.urls import path
from libros.views import lista_libros, libros_create, lista_autores, LibroDetail, LibroUpdate, LibroDelete, Nosotros
#from config import views

app_name = "libros"
urlpatterns = [
    path("", Nosotros, name="nosotros"),
    path("libros/lista",lista_libros, name="lista_libros"),
    path("libros/create",libros_create,name="libros_create"),
    path("libros/autores",lista_autores,name="lista_autores"),
    path("libros/detail/<int:pk>",LibroDetail.as_view(),name="libro_detail") ,
    path("libros/update/<int:pk>",LibroUpdate.as_view(),name="libro_update"),
    path("libros/delete/<int:pk>",LibroDelete.as_view(),name="libro_delete")
]

proyecto/libros/models.py
from django.db import models

class Editorial(models.Model):
    nombre = models.CharField(max_length=100,unique=True)

    def __str__(self):
        return self.nombre
    
    
class Libro(models.Model):
    nombre_libro = models.CharField(max_length=100,unique=True)
    autor = models.CharField(max_length=200,null=True,blank=True)
    año = models.PositiveBigIntegerField(null=True,blank=True)
    editorial = models.ForeignKey(Editorial,on_delete=models.SET_NULL, null=True,blank=True)
    unidades = models.IntegerField(null=True,blank=True)
    precio = models.DecimalField(max_digits=10,decimal_places=2,null=True,blank=True)
    numero_paginas = models.PositiveBigIntegerField(null=True,blank=True)
    genero = models.CharField(max_length=100,null=True,blank=True)
    
    def __str__(self) -> str:
        return self.nombre_libro
    
class Autores(models.Model):
    nombre_autor = models.CharField(max_length=200)
    libros = models.ManyToManyField(Libro)
    nacionalidad = models.CharField(max_length=100,null=True,blank=True)
    nacimiento = models.DateField(null=True,blank=True)
    
    def __str__(self):
        return self.nombre_autor

  
           

proyecto/libros/forms.py
from django import forms
from . import models

class LibroForms(forms.ModelForm):
    class Meta:
        model = models.Libro
        fields = "__all__"

proyecto/libros/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from libros.models import Libro, Autores
from libros.forms import LibroForms
from django.views.generic import DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy

def Nosotros(request):
    return render(request,"libros/nosotros.html")

def lista_libros(request):
    busqueda = request.GET.get("busqueda", None)
    if busqueda:
        consulta = Libro.objects.filter(Q(nombre_libro__icontains=busqueda) | Q(autor__icontains=busqueda))
    else:
        consulta = Libro.objects.all()
    contexto = {"libros": consulta}
    return render(request, "libros/lista_libros.html", contexto)


def libros_create(request):
    if request.method == "POST":
        form = LibroForms(request.POST)
        if form.is_valid():
            form.save()
            return redirect("libros:lista_libros")
    else:
        form = LibroForms()
    return render(request,"libros/libro_form.html",{"form":form})

def lista_autores(request):
    busqueda = request.GET.get("busqueda",None)
    if busqueda:
        print(busqueda)
        consulta = Autores.objects.filter(nombre_autor__icontains=busqueda)
    else:
       consulta = Autores.objects.all()
    contexto = {"autores": consulta}
    return render(request,"libros/lista_autores.html",contexto)

class LibroDetail(DetailView):
    model = Libro

class LibroUpdate(UpdateView):
    model = Libro
    form_class = LibroForms
    success_url = reverse_lazy("libros:lista_libros")

class LibroDelete(DeleteView):
    model = Libro
    success_url = reverse_lazy("libros:lista_libros")

    

 

proyecto/libros/templates/libros/libro_confirm_delete.html
{% extends 'core/base.html' %}
   
{% block titulo %}
       Eliminar libro
 {% endblock titulo %}

 {% block body_title %}
      Libros - Eliminar Libro
 {% endblock body_title %}

{% block contenido %}
   <p class="fs-5"><span style="font-family: 'Georgia', serif;">¿Seguro que desea eliminar "{{ object.nombre_libro }}"?</span></p>
   <form action="" method="post">
    {% csrf_token %}
    <button type="submit">Eliminar</button>
   </form>
   <a href="{% url 'libros:lista_libros' %}" class="btn btn-secondary btn-sm">Volver</a>
 {% endblock contenido %}

proyecto/libros/templates/libros/libro_detail.html
{% extends 'core/base.html' %}
  
{% block titulo %}
    Lista de Libros
{% endblock titulo %}

{% block body_title %}
    Detalle Del Libro
{% endblock body_title %}

{% block contenido %}
    <div class="container contenido mb-5">
        <ul class="list-group">
            <li class="list-group-item">
                <p class="fs-4 mb-0 font-weight-bold">{{libro.nombre_libro}}</p>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item fs-6"><span class="font-weight-bold">Autor:</span> {{libro.autor}}</li>
                    <li class="list-group-item fs-6"><span class="font-weight-bold">Año:</span> {{libro.año}}</li>
                    <li class="list-group-item fs-6"><span class="font-weight-bold">Editorial:</span> {{libro.editorial}}</li>
                    <li class="list-group-item fs-6"><span class="font-weight-bold">Género:</span> {{libro.genero}}</li>
                    <li class="list-group-item fs-6"><span class="font-weight-bold">Páginas:</span> {{libro.paginas}}</li>
                    {% if libro.unidades %}
                    <li class="list-group-item fs-6"><span class="font-weight-bold">Unidades:</span> {{libro.unidades}}</li>
                    {% else %}
                    <li class="list-group-item fs-6"><span class="font-weight-bold">Unidades:</span> No Disponible</li>
                    {% endif %}
                    
                    <li class="list-group-item fs-6"><span class="font-weight-bold">Precio:</span> ${{libro.precio}}</li>
                </ul>
            </li>
        </ul>
        <a href="{% url 'libros:lista_libros' %}" class="btn btn-dark mt-3">Volver</a>
    </div>
    
{% endblock contenido %}

proyecto/libros/templates/libros/libro_form.html
{% extends 'core/base.html' %}
   
{% block titulo %}
    Agregar libro
 {% endblock titulo %}

 {% block body_title %}
      {% if form.instance.pk %}
      Libro - Editar Libro
      {% else %}
      Libro - Agregar Nuevo Libro
      {% endif %}
 {% endblock body_title %}

 {% block contenido %}
 <form action="" method="post">
  {% csrf_token %}
  {{ form }}
 <div style="margin-top: 10px;">
       <a href="{% url 'libros:lista_libros' %}" class="btn btn-secondary btn-sm">Volver</a>
      <button type="submit" class="btn btn-info btn-sm me-2">Guardar</button> 
 </div>
</form>
{% endblock contenido %}

proyecto/libros/templates/libros/libros_create.html
{% extends 'core/base.html' %}
   
{% block titulo %}
    <h1>Agregar libro</h1>
 {% endblock titulo %}

 {% block body_title %}
        Agregar un libro
 {% endblock body_title %}

{% block contenido %}
   <form action="" method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit">Guardar</button>
   </form>
    <button><a href="{% url 'libros:index' %}">Volver a libros</a></button>
 {% endblock contenido %}

proyecto/libros/templates/libros/lista_autores.html
{% extends 'core/base.html' %}

{% block titulo %}
    <h1>Lista de Autores</h1>
{% endblock titulo %}

{% block body_title %}
    Listado De Autores       
{% endblock body_title %}

{% block contenido %}
<form class="mb-3 row" action="{% url 'libros:lista_autores' %}" method="get">
    <div class="col-auto">
        <input type="text" class="form-control" name="busqueda" placeholder="Buscar autor...">
    </div>
    <div class="col-auto">
        <button type="submit" class="btn btn-dark ">Buscar</button>
    </div>
</form>
<div class="row contenido mb-5">
    {% for autor in autores %}
    <div class="col-md-4 mb-4">
        <div class="card">
            <div class="card-body">
                <p class="fs-4 mb-0 font-weight-bold">{{ autor.nombre_autor }}</p>
                <p class="card-text small"><strong>Nacionalidad:</strong> {{ autor.nacionalidad }}</p>
                <p class="card-text small"><strong>Nacimiento:</strong> {{ autor.nacimiento }}</p>
                <button class="btn btn-dark  ver-libros-btn" type="button" data-toggle="collapse" data-target="#listaLibros{{ forloop.counter }}">Libros Disponibles</button>
                <div id="listaLibros{{ forloop.counter }}" class="collapse">
                    <ul class="list-group mt-3">
                        {% if autor.libros.all %}
                        {% for libro in autor.libros.all %}
                        <li class="list-group-item libro">{{ libro.nombre_libro }}</li>
                        {% endfor %}
                        {% else %}
                        <li class="list-group-item">No hay libros disponibles para este autor.</li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<script>
    $('.ver-libros-btn').click(function() {
        $(this).text(function(i, text) {
            return text === "Libros Disponibles" ? "Ocultar Libros" : "Libros Disponibles";
        });
    });
</script>
{% endblock contenido %}

proyecto/libros/templates/libros/lista_libros.html
{% extends 'core/base.html' %}
  
{% block titulo %}
    Libros
{% endblock titulo %}

{% block body_title %}
    Catalogo De libros
{% endblock body_title %}

{% block contenido %}
<form class="mb-3 row" action="{% url 'libros:lista_libros' %}" method="get">
    <div class="col-auto">
        <input type="text" class="form-control" name="busqueda" placeholder="Buscar libro...">
    </div>
    <div class="col-auto">
        <button type="submit" class="btn btn-dark">Buscar</button>
    </div>
</form>
<div class="d-flex justify-content-between align-items-center mb-3">
    <h2>Libros</h2>
    {% if user.is_authenticated %}
    <button class="btn btn-lg btn-dark my-button"><a href="{% url 'libros:libros_create' %}" style="color:white;">Agregar libro</a></button>
    {% endif %}
</div>
<ul class="list-group contenido mb-5">
    {% for libro in libros %}
    <li class="list-group-item">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <span style="font-family: 'Georgia', serif; font-size: 1.1em;">{{libro.nombre_libro}}</span>
            </div>
            <div class="d-flex align-items-center">
                <span class="me-3" style="font-family: 'Montserrat', sans-serif; font-size: 0.9em;"><strong>$</strong>{{libro.precio}}</span>
                <div>
                    {% if user.is_authenticated %}
                    <a href="{% url 'libros:libro_detail' libro.id %}" class="btn btn-dark btn-sm me-2">Ver Detalle</a>
                    <a href="{% url 'libros:libro_update' libro.id %}" class="btn btn-secondary btn-sm me-2">Cambiar</a>
                    <a href="{% url 'libros:libro_delete' libro.id %}" class="btn btn-secondary btn-sm">Borrar</a>
                    {% else %}
                    <a href="{% url 'libros:libro_detail' libro.id %}" class="btn btn-dark btn-sm">Ver Detalle</a>
                    <button type="submit" class="btn btn-info ">Comprar</button>
                    {% endif %}
                </div>
            </div>
        </div>
    </li>
{% endfor %}
</ul>
{% endblock contenido %}

proyecto/libros/templates/libros/nosotros.html
{% extends 'core/base.html' %}

{% block titulo %}
    Nosotros
 {% endblock titulo %}

 {% block body_title %}
      ¿Quienes somos?      
 {% endblock body_title %}

 {% block contenido %}
<div class="container contenido mb-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="text-center">
                <!-- Contenido de la librería Leone -->
                <p class="font-weight-bold">Bienvenidos a Librería Leone, tu destino literario en la vibrante ciudad de Rosario.</p>
                <p class="font-weight-normal">Con tres sucursales repartidas estratégicamente por la ciudad, nos enorgullece ser tu fuente confiable de exploración literaria desde 1994.</p>
                <p class="font-weight-normal">En Librería Leone, nuestra pasión es conectar lectores con historias cautivadoras. Es por eso que ofrecemos una amplia selección de libros que abarcan todos los géneros imaginables.</p>
                <p class="font-weight-normal">Desde clásicos atemporales hasta los últimos lanzamientos de los más aclamados autores contemporáneos, tenemos algo para cada lector ávido de descubrimiento. Ya sea que busques un thriller de suspenso para mantener tus pulsaciones aceleradas o una conmovedora historia de amor para calmar tu corazón, estamos aquí para ayudarte a encontrar el libro perfecto que complemente tu estado de ánimo y tus intereses.</p>
                <p class="font-weight-normal">Nuestro equipo está formado por apasionados bibliófilos que están siempre dispuestos a ofrecerte recomendaciones personalizadas y a compartir sus conocimientos sobre la vasta y maravillosa gama de libros que albergamos en nuestras estanterías.</p>
                <p class="font-weight-normal"> Te invitamos a explorar nuestras sucursales, sumergirte en la atmósfera acogedora y repleta de historias que hemos creado para ti, y dejarte llevar por la magia de la literatura en Librería Leone. ¡Esperamos verte pronto entre nuestras páginas!</p>
                
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}